---
  - name: Update cache
    apt: update_cache=yes cache_valid_time=3600

  - name: Install haproxy
    apt: name=haproxy state=present

  - name: Configure haproxy.cfg
    template:
      src: "haproxy.cfg.j2"
      dest: "/etc/haproxy/haproxy.cfg"
    notify: restart haproxy

  - name: Enable init script
    replace: 
      dest='/etc/default/haproxy' 
      regexp='ENABLED=0'
      replace='ENABLED=1'